=== ironlanderl/EsTPSIT2/Pardini_Fabrizio_5CM_2022-02-19_EsFilm/Pardini_Fabrizio_5CM_2022-02-19_EsFilm.dtd
<!-- Pardini_Fabrizio_5CM_2022-02-19_EsFilm-->
<!ELEMENT catalogo (film*)>
<!ELEMENT film (titolo,regista+,attore*,genere?)>
<!ELEMENT titolo (#PCDATA)>
<!ELEMENT regista (nome,cognome)>
<!ELEMENT attore (nome,cognome)>
<!ELEMENT genere (#PCDATA)>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT cognome (#PCDATA)>

<!ATTLIST film cod ID #REQUIRED
               originale (si|no) #REQUIRED
               formato (VHS|DVD|DIVX) #REQUIRED
               voto CDATA #IMPLIED>

=== ironlanderl/EsTPSIT2/Pardini_Fabrizio_5CM_2022-02-19_EsFilm/Pardini_Fabrizio_5CM_2022-02-19_EsFilm.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalogo SYSTEM "Pardini_Fabrizio_5CM_2022-02-19_EsFilm.dtd">
<!-- Pardini_Fabrizio_5CM_2022-02-19_EsFilm-->
<catalogo>
    <film cod="tt9419884" originale="si" formato="DIVX" voto="8">
        <titolo>Doctor Strange</titolo>
        <regista>
            <nome>Sam</nome>
            <cognome>Raimi</cognome>
        </regista>
        <attore>
            <nome>Benedict</nome>
            <cognome>Cumberbatch</cognome>
        </attore>
        <genere>Azione</genere>
    </film>
    <film cod="tt1464335" originale="no" formato="DVD">
        <titolo>Uncharted</titolo>
        <regista>
            <nome>Ruben</nome>
            <cognome>Fleischer</cognome>
        </regista>
        <attore>
            <nome>Tom</nome>
            <cognome>Holland</cognome>
        </attore>
        <attore>
            <nome>Mark</nome>
            <cognome>Vahlberg</cognome>
        </attore>
        <genere>Avventura</genere>
    </film>
</catalogo>
