=== ironlanderl/EsTPSIT2/Pardini_Fabrizio_5CM_2022-02-19_EsFilm/Pardini_Fabrizio_5CM_2022-03-04_EsFilmSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Pardini_Fabrizio_5CM_2022-03-04_EsFilmSchema-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="catalogo">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="film" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titolo" type="xs:string"></xs:element>
                            <xs:element name="regista" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nome" type="xs:string"></xs:element>
                                        <xs:element name="cognome" type="xs:string"></xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="attore" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nome" type="xs:string"></xs:element>
                                        <xs:element name="cognome" type="xs:string"></xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="genere" type="xs:string" minOccurs="0" maxOccurs="1"></xs:element>
                        </xs:sequence>
                        <xs:attribute name="codice" type="xs:string"></xs:attribute>
                        <xs:attribute name="originale">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="si"></xs:enumeration>
                                    <xs:enumeration value="no"></xs:enumeration>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="formato">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="VHS"></xs:enumeration>
                                    <xs:enumeration value="DVD"></xs:enumeration>
                                    <xs:enumeration value="DIVX"></xs:enumeration>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="voto" use="optional">
                            <xs:simpleType>
                                <xs:restriction base="xs:integer">
                                    <xs:minInclusive value="0"></xs:minInclusive>
                                    <xs:maxInclusive value="10"></xs:maxInclusive>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ironlanderl/EsTPSIT2/Pardini_Fabrizio_5CM_2022-02-19_EsFilm/Pardini_Fabrizio_5CM_2022-03-04_EsFilmSchema.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Pardini_Fabrizio_5CM_2022-03-04_EsFilmSchema-->
<catalogo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Pardini_Fabrizio_5CM_2022-03-04_EsFilmSchema.xsd">
    <film codice="tt9419884" originale="si" formato="DIVX" voto="8">
        <titolo>Doctor Strange</titolo>
        <regista>
            <nome>Sam</nome>
            <cognome>Raimi</cognome>
        </regista>
        <attore>
            <nome>Benedict</nome>
            <cognome>Cumberbatch</cognome>
        </attore>
        <genere>Azione</genere>
    </film>
    <film codice="tt1464335" originale="no" formato="DVD">
        <titolo>Uncharted</titolo>
        <regista>
            <nome>Ruben</nome>
            <cognome>Fleischer</cognome>
        </regista>
        <attore>
            <nome>Tom</nome>
            <cognome>Holland</cognome>
        </attore>
        <attore>
            <nome>Mark</nome>
            <cognome>Vahlberg</cognome>
        </attore>
        <genere>Avventura</genere>
    </film>
</catalogo>
