=== ironlanderl/EsTPSIT2/Pardini_Fabrizio_5CM_2022-03-03_Libreria/Pardini_Fabrizio_5CM_2022-03-04_LibreriaSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Pardini_Fabrizio_5CM_2022-03-03_LibreriaSchema-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="libreria">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="libro">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id" type="xs:string"></xs:element>
                            <xs:element name="titolo" type="xs:string"></xs:element>
                            <xs:element name="edizione">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="1"></xs:minInclusive>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="autore" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nome" type="xs:string"></xs:element>
                                        <xs:element name="cognome" type="xs:string"></xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="casaEditrice" type="xs:string"></xs:element>
                            <xs:element name="annoPubblicazione" type="xs:integer"></xs:element>
                            <xs:element name="prezzo" type="xs:string"></xs:element>
                            <xs:element name="pezzi">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="0"></xs:minInclusive>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="sconto" minOccurs="0" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="percentuale">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:integer">
                                                    <xs:minInclusive value="0"></xs:minInclusive>
                                                    <xs:maxExclusive value="100"></xs:maxExclusive>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="da" type="xs:date"></xs:element>
                                        <xs:element name="a" type="xs:date"></xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ironlanderl/EsTPSIT2/Pardini_Fabrizio_5CM_2022-03-03_Libreria/Pardini_Fabrizio_5CM_2022-03-04_LibreriaSchema.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Pardini_Fabrizio_5CM_2022-03-03_LibreriaSchema-->
<libreria xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Pardini_Fabrizio_5CM_2022-03-04_LibreriaSchema.xsd">
    <libro>
        <id>INF01US</id>
        <titolo>Designing the User Interface</titolo>
        <edizione>4</edizione>
        <autore>
            <nome>Ben</nome>
            <cognome>Shneiderman</cognome>
        </autore>
        <autore>
            <nome>Catherine</nome>
            <cognome>Plaisant</cognome>
        </autore>
        <casaEditrice>Addison-Wesley</casaEditrice>
        <annoPubblicazione>2003</annoPubblicazione>
        <prezzo>76$</prezzo>
        <pezzi>10</pezzi>
        <sconto>
            <percentuale>7</percentuale>
            <da>2004-03-01</da>
            <a>2004-06-01</a>
        </sconto>
    </libro>
</libreria>
