=== ironlanderl/EsTPSIT2/Pardini_Fabrizio_5CM_2022-03-03_Libreria/Pardini_Fabrizio_5CM_2022-03-03_Libreria.dtd
<!-- Pardini_Fabrizio_5CM_2022-03-03_Libreria-->
<!ELEMENT libreria (libro)>
<!ELEMENT libro (id, titolo, edizione, autore+, casaEditrice, annoPubblicazione, prezzo, pezzi, sconto?)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT titolo (#PCDATA)>
<!ELEMENT edizione (#PCDATA)>
<!ELEMENT autore (nome, cognome)>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT cognome (#PCDATA)>
<!ELEMENT casaEditrice (#PCDATA)>
<!ELEMENT annoPubblicazione (#PCDATA)>
<!ELEMENT prezzo (#PCDATA)>
<!ELEMENT pezzi (#PCDATA)>
<!ELEMENT sconto (percentuale, da, a)>
<!ELEMENT percentuale (#PCDATA)>
<!ELEMENT da (giorno, mese, anno)>
<!ELEMENT a (giorno, mese, anno)>
<!ELEMENT giorno (#PCDATA)>
<!ELEMENT mese (#PCDATA)>
<!ELEMENT anno (#PCDATA)>

<!ATTLIST prezzo valuta (eur|usd|gbp) #REQUIRED>

=== ironlanderl/EsTPSIT2/Pardini_Fabrizio_5CM_2022-03-03_Libreria/Pardini_Fabrizio_5CM_2022-03-03_Libreria.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Pardini_Fabrizio_5CM_2022-03-03_Libreria-->
<!DOCTYPE libreria SYSTEM "Pardini_Fabrizio_5CM_2022-03-03_Libreria.dtd">
<libreria>
    <libro>
        <id>INF01US</id>
        <titolo>Designing the User Interface</titolo>
        <edizione>Quarta</edizione>
        <autore>
            <nome>Ben</nome>
            <cognome>Shneiderman</cognome>
        </autore>
        <autore>
            <nome>Catherine</nome>
            <cognome>Plaisant</cognome>
        </autore>
        <casaEditrice>Addison-Wesley</casaEditrice>
        <annoPubblicazione>2003</annoPubblicazione>
        <prezzo valuta="usd">76</prezzo>
        <pezzi>10</pezzi>
        <sconto>
            <percentuale>7</percentuale>
            <da>
                <giorno>01</giorno>
                <mese>03</mese>
                <anno>2004</anno>
            </da>
            <a>
                <giorno>01</giorno>
                <mese>06</mese>
                <anno>2004</anno>
            </a>
        </sconto>
    </libro>
</libreria>
